# Generated by Django 4.0.2 on 2023-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Ceramics', 'Ceramics'), ('Conceptual art', 'Conceptual art'), ('Drawing', 'Drawing'), ('Painting', 'Painting'), ('Photography', 'Photography'), ('Sculpture', 'Sculpture')], max_length=30),
        ),
    ]
