# Generated by Django 4.0.2 on 2023-05-28 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 28, 17, 5, 51, 416232)),
        ),
    ]
